### ISSUE TITLE
Commit approved with prefix "UPSTREAN"

### ISSUE THREAD

**Issue by ddavenport-chromium** [atseanpaul/review-o-matic#29]
See https://crrev.com/c/3489178/5

Ideally the script could tell the uploader when an unknown prefix is used. At the very least, the script should withhold its +1 in this case.

**Comment by atseanpaul** [comment]
This one is kind of hard b/c the prefix changed after the successful review. So when the +1 was given, the prefix was correct.

In future revisions, the script didn't even pick it up b/c the prefix had changed. The +1 was sticky since nothing else had changed.

I think we could find a clever (but possibly intensive) solution to this, but I'm not sure it'd be worthwhile.

**Comment by ddavenport-chromium** [comment]
That's what I suspected as well, but I didn't see the correct prefix when I looked back at previous patch sets in Gerrit. Maybe I'm just doing it wrong?

Actually looks like a Gerrit UI confusion issue. If I look at a specific patches a-la https://crrev.com/c/3489178/2, it shows "UPSTREAN". But if I look at the commit for that patchset directly https://crrev.com/23e9dbba5213edab1943c5119d44bd0e379d3103, it shows the correct prefix.

So I understand this is not a bug in the review tool, and any solution would more be a FR to detect/deal with invalid prefixes in general.
